sudo: false

language: generic

cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test
- stack install

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ~/.local/bin/goal
  skip_cleanup: true
  on:
    tags: true

