name:                goal
version:             0.1.0.0
synopsis:            Manage projects one goal at a time
description:         Manage projects one goal at a time
homepage:            https://github.com/cloud8421/goal#readme
license:             BSD3
author:              Claudio Ortolina
maintainer:          cloud8421@gmail.com
copyright:           2018 Claudio Ortolina
category:            Web
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-casing
- blaze-html
- exceptions
- file-embed
- http-types
- monad-logger
- optparse-applicative
- persistent
- persistent-sqlite
- persistent-template
- servant-server
- servant-blaze
- text
- wai
- wai-extra
- wai-logger
- wai-middleware-static-embedded
- wai-middleware-static
- warp

library:
  source-dirs: src
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  goal:
    source-dirs: src
    main: Main.hs
    dependencies:
    - goal
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  goal-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - goal
    - directory
    - hspec >=2.0.0
    - hspec-wai
    - hspec-wai-json
    - microlens
    - bytestring

flags:
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
